language: python
python:
  - "pypy3.5"
install:
  - source ~/virtualenv/python3.6/bin/activate
  - pip install mypy flake8
script:
  - ls -la ~/virtualenv
  - PATH=~/virtualenv/pypy3.5/bin:$PATH mypy hase tests/benchmark
  - flake8 hase
branches:
  only:
  - master

#language: nix
#script:
#  - nix run --quiet nixpkgs.python3Packages.mypy -c mypy hase
#  # too slow at the moment, needs caching
#  #  - nix-shell --quiet --command "virtualenv venv && . ./venv/bin/activate && pip install --quiet --process-dependency-links -e '.[test]'"
